### ISSUE TITLE
Almost a JS

### ISSUE THREAD

**Issue by c-smile** [lemon-lang/lemon#10]
Looks like Lemon is close to JS so why not to make it as a subset of JS?

**Comment by zhicheng** [comment]
JS is also close to Java, Java is also close to C++, C++ is also close to C. This is no point question.

**Comment by c-smile** [comment]
I am not against Lemon syntax per se. Just a learning curve consideration for new people.
At least I would implement JS runtime library: Array, String, Object methods with familiar signatures.

Source code and architecture looks clean and nice so it may evolve to something interesting.
But problem is that you have plenty other competitors from micro JS implementations to big ones.
So either you will provide some unique features or super small and effective implementation of existing language. Some selling point is required to be short.

**Comment by zhicheng** [comment]
I have zero intention make Lemon replace JavaScript.The syntax is familiar like JS is not a because Lemon syntax like JS.It's becuase JS's syntax like others.

I'm a C developer,so the syntax is very straight forward, also I'm not interested invent some weird syntax just let people think Lemon is different,just quite opposite I'd like people use it smoothly.

The competitor from JS is absurd,If someone use JS very well, they have no reason replace to Lemon. if someone will give Lemon a try, they can always fallback to JS, everyone happy, right?

if you want discuss more about Lemon, I suggest open a topic in https://groups.google.com/d/forum/lemon-lang I'd be happy to answer anything about Lemon, Thanks.
